### PR TITLE
Revert "use a lexical variable to prevent external fondling"

### PR DESCRIPTION
**Pull request by haarg**
This reverts commit 8447a3bf0e1b88bdd07fa584d83c81c64ad192cf.

Using a arrayref causes segfaults in the t/global_destruction_forked.t
on Windows in Perls < 5.20.

### CODE REVIEW

**Comment by karenetheridge** [comment]
@mauke

**Comment by haarg** [comment]
Example failure: http://www.cpantesters.org/cpan/report/a9078b15-6c01-1014-8821-30a0e94294f0

I tried a few other ways to make this work, but didn't come up with anything.

**Comment by karenetheridge** [comment]
Also cc @ribasushi, since he asked for this change.  Ideas for alternative implementations?

**Comment by mauke** [comment]
I can reproduce this problem. The test is doing

``` perl
try {
print STDERR "[$$] in try {}\n";
  my $pid = fork;
print STDERR "[$$] after fork\n";
  unless ($pid) {
    my $o = bless {}, 'WithCatch';
```

(I manually added the `print STDERR`s.)

perl is crashing (`c0000005`, access violation, at offset `c12af`) inside the `fork`:

```
C:>perl -Mblib t/global_destruction_forked.t
1..3
[6252] in try {}

C:>
```

**Comment by mauke** [comment]
WTF, even this crashes:

```
C:>perl -e "local $x[0] = 42; fork"
panic: ss_dup inconsistency (21) at -e line 1.
```

**Comment by ribasushi** [comment]
> Also cc @ribasushi, since he asked for this change. Ideas for alternative implementations?

I would start with dropping the exotics of a localized array element and checking how things behave with a localized hash key.

**Comment by karenetheridge** [comment]
@exodist pointed me to: https://metacpan.org/source/EXODIST/Test2-0.000030/lib/Test2/Util.pm#L81

**Comment by exodist** [comment]
now I wish I included the ticket number in that comment, let me find it...

**Comment by exodist** [comment]
https://rt.perl.org/Public/Bug/Display.html?id=40565

**Comment by haarg** [comment]
I tried with a hash instead, and I'm not seeing any crashes, so I've submitted that as #3.

**Comment by karenetheridge** [comment]
closed in favour of #3.

**Pull request closed without merging**
